### ISSUE TITLE
Ghost ping is detected when it's not supposed to be.

### ISSUE THREAD

**Issue by Sujal1234** [Anti-Ghost-Ping/bug-reports#3]
**Describe the bug**

If a message contains a ping and we edit the message and add another ping, i.e, ping another person but keep the old ping too then the bot gets triggered.

**To Reproduce**

1. Type a message and ping someone in it. E.g "@user1".
2. Edit the message and add another ping to it. E.g "@user1 @user2".
3. Now the bot gets triggered and shows the first message ("@user1") in the embed.

**Expected behavior**

The expected behavior is that nothing should happen and the bot should not be triggered.

**Comment by Leastrio** [comment]
Fixed.
